registry:
  models:
    - model_id: "google:gemini-1.5-pro"
      model_name: "gemini-1.5-pro"
      cost:
        input_cost_per_million: 3500
        output_cost_per_million: 10500
      rate_limit:
        tokens_per_minute: 1000000
        requests_per_minute: 1000
      provider:
        name: "Google"
        default_api_key: "${GOOGLE_API_KEY}"
        base_url: "https://api.google.com"
      api_key: null

    - model_id: "google:gemini-2.0-flash"
      model_name: "gemini-2.0-flash-thinking"
      cost:
        input_cost_per_million: 70
        output_cost_per_million: 300
      rate_limit:
        tokens_per_minute: 1000000
        requests_per_minute: 2000
      provider:
        name: "Google"
        default_api_key: "${GOOGLE_API_KEY}"
        base_url: "https://api.google.com"
      api_key: null

    - model_id: "google:gemini-exp-1206"
      model_name: "gemini-exp-1206"
      cost:
        input_cost_per_million: 5000
        output_cost_per_million: 15000
      rate_limit:
        tokens_per_minute: 500000
        requests_per_minute: 1000
      provider:
        name: "Google"
        default_api_key: "${GOOGLE_API_KEY}"
        base_url: "https://api.google.com"
      api_key: null